name: drip-woocommerce
services:
  web:
    build: .
    ports:
    - 3007:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=woocommerce
      - WORDPRESS_DB_USER=woocommerce
      - WORDPRESS_DB_PASSWORD=woocommerce
    volumes:
      - type: bind
        source: './..'
        target: /var/www/html/wp-content/plugins/drip
        consistency: cached
  db:
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=woocommerce
      - MYSQL_USER=woocommerce
      - MYSQL_PASSWORD=woocommerce
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
    - 3307:3306
    volumes: 
      - ./db_data/mysql:/var/lib/mysql
  mock:
    image: mockserver/mockserver:mockserver-5.14.0
    # We need to use port 8080 for WP webhooks to work.
    command: ["-logLevel", "INFO", "-serverPort", "8080"]
    ports:
    - 1080:8080
